// react/reactapuestas/src/components/Menu.jsx
import React, { Component } from 'react'
import { NavLink } from 'react-router-dom'
import Global from '../Global';
import axios from 'axios';

export default class Menu extends Component {
    state = {
        equipos: []
    }

    loadEquipos = () => {
        let request = "api/equipos";
        let url = Global.apiApuestas + request;

        axios.get(url).then(response => {
            this.setState({
                equipos: response.data
            })
        })
    }



    componentDidMount = () => {
        this.loadEquipos();
    }

    componentDidUpdate = (oldProps) => {
        if (this.props !== oldProps) {
            this.loadEquipos();
        }
    }

    render() {
        return (
            <div>
                <nav className="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
                    <div className="container-fluid">
                        <NavLink className="navbar-brand" to="/">Apuestas 🐲</NavLink>
                        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>
                        <div className="collapse navbar-collapse" id="navbarsExample03">
                            <ul className="navbar-nav me-auto mb-2 mb-sm-0">
                                <li className="nav-item">
                                    <NavLink className="nav-link active" aria-current="page" to="/">Home</NavLink>
                                </li>
                                <li className="nav-item">
                                    <NavLink className="nav-link" to="/apuestas">Bets</NavLink>
                                </li>
                                <li className="nav-item">
                                    <NavLink className="nav-link" to="/create">New bet</NavLink>
                                </li>
                                <li className="nav-item dropdown">
                                    <NavLink className="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Equipos</NavLink>
                                    <ul className="dropdown-menu">
                                        {
                                            this.state.equipos.map((equipo, i) => {
                                                return (
                                                    <li key={i}><NavLink className="dropdown-item" to={"/equipos/" + equipo.idEquipo}>{equipo.nombre}</NavLink></li>
                                                )
                                            })
                                        }
                                    </ul>
                                </li>
                                {/* <li className="nav-item">
                                    <NavLink className="nav-link" to="/departamentos" target="_blank">Departamentos</NavLink>
                                </li> */}
                                {/* <li className="nav-item dropdown">
                                    <NavLink className="nav-link dropdown-toggle" to="#" data-bs-toggle="dropdown" aria-expanded="false">Departamentos</NavLink>
                                    <ul className="dropdown-menu">
                                        {
                                            this.state.departamentos.map((hospital, i) => {
                                                return (
                                                    <li key={i}>
                                                        <NavLink className="dropdown-item btn-success" to={"/doctores/" + hospital.idhospital}>{hospital.nombre}</NavLink>
                                                    </li>
                                                )
                                            })
                                        }
                                    </ul>
                                </li> */}
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        )
    }
}

// vue/vue07series/src/components/MenuComponent.vue
<template>
    <div class="home">
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
            <div class="container-fluid">
                <router-link class="navbar-brand" to="/">Series 🐲</router-link>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarsExample03">
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                            <router-link class="nav-link active" aria-current="page" to="/">Home</router-link>
                        </li>
                        <li class="nav-item">
                            <router-link class="nav-link" to="/create">Nuevo personaje</router-link>
                        </li>
                        <li class="nav-item">
                            <router-link class="nav-link" to="/update">Modificar personaje</router-link>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" >
                                <li v-for="serie in series" :key="serie"><router-link class="dropdown-item" :to="'/serie/' +
                                    serie.idSerie">{{ serie.nombre }}</router-link></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>



    </div>
</template>

<script>
import ServiceSeries from '@/services/ServiceSeries';
const service = new ServiceSeries();

export default {
    name: 'MenuComponent',
    data() {
        return {
            series: []
        }
    },
    mounted() {
        service.getSeries().then(response => {
            this.series = response;
        });
    }

}
</script>

<style></style>
