// vue/vue06coches/src/components/CreateCoche.vue
<template>
  <div class="d-flex justify-content-center">
        <form class="d-flex justify-content-around align-items-center w-50 bg-primary-subtle gap-3 p-5" v-on:submit.prevent="crearCoche()">
            <input type="text" v-model="coche.idCoche" placeholder="id" class="form-control w-25" />
            <input type="text" v-model="coche.modelo" placeholder="modelo" class="form-control w-25" />
            <input type="text" v-model="coche.marca" placeholder="marca" class="form-control w-25" />
            <input type="text" v-model="coche.conductor" placeholder="conductor" class="form-control w-25" />
            <input type="text" v-model="coche.imagen" placeholder="img" class="form-control w-25" />
            <br />
            <button class="btn btn-outline-dark m-3">Crear</button>
        </form>
    </div>
</template>

<script>
import ServicesCoches from '@/services/ServiceCoches';
const service = new ServicesCoches();

export default {
    name: "CreateCoche",
    data(){
        return{
            coche: {
                idCoche: 0,
                modelo: "",
                marca: "",
                conductor: "",
                imagen: ""
            }
        }
    },
    methods:{
        crearCoche(){
            service.createCoche(this.coche).then(result=>{
                console.log(result);
                this.$router.push('/');
            });
        }
    }
}
</script>

<style>

</style>

// react/reactcrudcoches/src/components/CreateCoche.jsx
import React, { Component } from 'react'
import Global from '../Global';
import axios from 'axios';
import { Navigate } from 'react-router-dom';

export default class CreateCoche extends Component {
    cajaId = React.createRef();
    cajaMarca = React.createRef();
    cajaModelo = React.createRef();
    cajaConductor = React.createRef();
    cajaImagen = React.createRef();

    state = {
        status: false
    }

    crearCoche = (e) => {
        e.preventDefault();
        let coche = {
            idCoche: parseInt(this.cajaId.current.value),
            marca: this.cajaMarca.current.value,
            modelo: this.cajaModelo.current.value,
            conductor: this.cajaConductor.current.value,
            imagen: this.cajaImagen.current.value
        }

        let request = "api/coches/insertcoche"
        let url = Global.apiCoches + request

        axios.post(url, coche).then(response => {
            this.setState({
                status: true
            })
        }) 
    }
    


  render() {
    return (
      <div>
        {
            this.state.status === true ?
            (<Navigate to="/"/>):(
                <form onSubmit={this.crearCoche}>
                    <input type="text" ref={this.cajaId} className='form-control' placeholder='ID'/>
                    <input type="text" ref={this.cajaMarca} className='form-control' placeholder='Marca'/>
                    <input type="text" ref={this.cajaModelo} className='form-control' placeholder='Modelo'/>
                    <input type="text" ref={this.cajaConductor} className='form-control' placeholder='Conductor'/>
                    <input type="text" ref={this.cajaImagen} className='form-control' placeholder='Imagen'/>
                    <button className='btn btn-outline-dark'>Crear coche</button>
                </form>
            )
        }
    </div>
    )
  }
}
