// vue/vue05cruddepartamentos/src/components/MenuComponent.vue
<template>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <router-link class="navbar-brand" to="/">Home</router-link>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><router-link class="nav-link" to="/"></router-link></li>
                        <li class="nav-item"><router-link class="nav-link" to="/coches">Coches</router-link></li>
                        <li class="nav-item"><router-link class="nav-link" to="/empleadosdetalle">Detalle
                                empleados</router-link></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Oficios
                            </a>
                            <ul class="dropdown-menu">
                                <!-- <li v-for="o in oficios" :key="o">
                                    <router-link class="dropdown-item" :to="'/oficiosdetalle/' + o">
                                        {{ o }}
                                    </router-link>
                                </li> -->
                            </ul>
                        </li>

                        <li class="nav-item"><a class="nav-link" href="#signup">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</template>

<script>
export default {
    name: "MenuComponent",

}
</script>

<style></style>

// angular/a6authlogin/src/app/components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from '../../../environments/environment';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent {
  constructor(private _router: Router) { }

  get isLogin(): boolean {
    return environment.isLogged;
  }

  logout() {
    environment.isLogged = false;
    this._router.navigate(['/login']);
  }
}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" [routerLink]="['/']">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                @if (isLogin){
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/perfil']">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <button class="nav-link" (click)="logout()">Logout</button>
                    </li>
                } @else {
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/login']">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/register']">Register</a>
                    </li>
                }
                
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        CRUDS
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" [routerLink]="['/coches']">Coches</a></li>
                        <li><a class="dropdown-item" [routerLink]="['/plantillas']">complex</a></li>
                    </ul>
                </li> -->
            </ul>
        </div>
    </div>
</nav>
