// vue/vue05cruddepartamentos/src/components/CreateDepartamento.vue
<template>
    <div class="d-flex justify-content-center">
        <form class="d-flex justify-content-around align-items-center w-50 bg-primary-subtle" v-on:submit.prevent="crearDepartamento()">
            <input type="text" v-model="departamento.idDepartamento" placeholder="id" class="form-control w-25" />
            <input type="text" v-model="departamento.nombre" placeholder="nombre" class="form-control w-25" />
            <input type="text" v-model="departamento.localidad" placeholder="localidad" class="form-control w-25" />
            <br />
            <button class="btn btn-outline-dark m-3">Crear</button>
        </form>
    </div>
</template>

<script>
import ServicesDepartamentos from '@/services/ServicesDepartamentos';
const service = new ServicesDepartamentos();

export default {
    name: "CreateDepartamento",
    data() {
        return {
            departamento: {
                idDepartamento: "",
                nombre: "",
                localidad: ""
            }

        }
    },
    methods:{
        crearDepartamento(){
            service.createDepartamento(this.departamento).then(response=>{
                console.log(response);
                this.$router.push("/");
            })
        }
    }

}
</script>

<style></style>

// react/reactcruddepartamentos/src/components/CreateDepartamento.jsx
import React, { Component } from 'react'
import Global from './Global';
import axios from 'axios';
import { Navigate } from 'react-router-dom';

export default class CreateDepartamento extends Component {
    cajaId = React.createRef();
    cajaNombre = React.createRef();
    cajaLocalidad = React.createRef();

    state = {
        status: false
    }

    insertarDepartamento = (e) => {
        e.preventDefault();
        let id = parseInt(this.cajaId.current.value)
        let nombre = this.cajaNombre.current.value
        let localidad = this.cajaLocalidad.current.value
        let departamento = {
            numero: id,
            nombre: nombre,
            localidad: localidad
        }

        let request = "api/departamentos"
        let url = Global.apiDepartamentos + request

        axios.post(url, departamento).then(response => {
            this.setState({
                status: true
            })
        }) 
    }


  render() {
    return (
      <div>
        {
            this.state.status === true ?
            (<Navigate to="/"/>):(
                <form onSubmit={this.insertarDepartamento}>
                    <input type="text" ref={this.cajaId} className='form-control' placeholder='ID'/>
                    <input type="text" ref={this.cajaNombre} className='form-control' placeholder='Nombre'/>
                    <input type="text" ref={this.cajaLocalidad} className='form-control' placeholder='Localidad'/>
                    <button className='btn btn-outline-dark'>Crear dept</button>
                </form>
            )
        }
      </div>
    )
  }
}
