// angular/a6authlogin/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { ServiceLogin } from '../../services/service.login';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  public isSignDivVisiable: boolean = true;

  public signUpObj: SignUpModel = new SignUpModel();
  public loginObj: LoginModel = new LoginModel();

  public userName: string = "";
  public password: string = "";

  constructor(private _router: Router, private _service: ServiceLogin) { }


  login(){
    this._service.getToken(this.userName, this.password).subscribe(response => {

        environment.token = response.response;
        this._router.navigate(['/empleados']);
      },
    error => {
      alert("Usuario o contraseña incorrecta");
    })
  }

  // onLogin() {
  //   // debugger;
  //   const localUsers = localStorage.getItem('angular17users');
  //   if (localUsers != null) {
  //     const users = JSON.parse(localUsers);

  //     const isUserPresent = users.find((user: SignUpModel) => user.email == this.loginObj.email && user.password == this.loginObj.password);
  //     if (isUserPresent != undefined) {
  //       alert("User Found...");
  //       localStorage.setItem('loggedUser', JSON.stringify(isUserPresent));
  //       this._router.navigate(['/perfil']);

  //     } else {
  //       alert("No User Found")
  //     }
  //   }
  // }

  onRegister() {
    debugger;
    const localUser = localStorage.getItem('angular17users');
    if (localUser != null) {
      const users = JSON.parse(localUser);
      users.push(this.signUpObj);
      localStorage.setItem('angular17users', JSON.stringify(users))
    } else {
      const users = [];
      users.push(this.signUpObj);
      localStorage.setItem('angular17users', JSON.stringify(users))
    }
    alert('Registration Success')
  }

}

export class SignUpModel {
  name: string;
  email: string;
  password: string;

  constructor() {
    this.email = "";
    this.name = "";
    this.password = ""
  }
}

export class LoginModel {
  email: string;
  password: string;

  constructor() {
    this.email = "";
    this.password = ""
  }


}


<div class="parent"> 
    <div class="container" [ngClass]="isSignDivVisiable ? 'active' :'' " id="container">
        <div class="form-container sign-up" >
            <form>
                <h1>Crear Cuenta</h1>
                <span>Introduzca nombre, mail y tipo de entidad</span>
                <input type="text" name="name" [(ngModel)]="signUpObj.name" placeholder="Nombre">
                <input type="email" name="email" [(ngModel)]="signUpObj.email" placeholder="Email">
                <input type="password" name="password"  [(ngModel)]="signUpObj.password" placeholder="Contraseña">
                <button (click)="onRegister()">Crear cuenta</button>
            </form>
        </div>
        <div class="form-container sign-in">
            <form>
                <h1>Iniciar Sesión</h1>
                <span>Introduzca apellido y contraseña</span>
                <input type="text" name="email" [(ngModel)]="userName" placeholder="Email">
                <input type="password" name="password"   [(ngModel)]="password" placeholder="Contraseña">
                <a href="#">→ ¿Olvidaste la contraseña? ←</a>
                <button (click)="login()">Acceder</button>
            </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>E V O bank</h1>
                    <p>¿Ya tienes una cuenta?</p>
                    <button type="button" class="hidden" id="login" (click)="isSignDivVisiable = false">Conectarse</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>E V O bank</h1>
                    <p>¿Aún no tienes cuenta?</p>
                    <button type="button" class="hidden" id="register" (click)="isSignDivVisiable = true">Crear cuenta</button>
                </div>
            </div>
        </div>
    </div>
</div>

// vue/vue08login/src/components/LoginComponent.vue
<template>
  <div>
    <div class="parent">
      <div class="container" :class="isSignDiv ? 'active' : ''"  id="container">
        <div class="form-container sign-up">
          <form>
            <h1>Crear Cuenta</h1>
            <span>Introduzca nombre, mail y tipo de entidad</span>
            <input type="text" name="name" v-model="signUpObj.name" placeholder="Nombre">
            <input type="email" name="email" v-model="signUpObj.email" placeholder="Email">
            <input type="password" name="password" v-model="signUpObj.password" placeholder="Contraseña">
            <button @click="onRegister()">Crear cuenta</button>
          </form>
        </div>
        <div class="form-container sign-in">
          <form v-on:submit.prevent="login()">
            <h1>Iniciar Sesión</h1>
            <span>Introduzca apellido y contraseña</span>
            <input type="text" name="email" v-model="userName" placeholder="Email">
            <input type="password" name="password" v-model="password" placeholder="Contraseña">
            <a href="#">→ ¿Olvidaste la contraseña? ←</a>
            <button >Acceder</button>
            <p v-if="token">{{ token }}</p>
          </form>
        </div>
        <div class="toggle-container">
          <div class="toggle">
            <div class="toggle-panel toggle-left">
              <h1>E V O bank</h1>
              <p>¿Ya tienes una cuenta?</p>
              <button type="button" class="hidden" id="login" @click="swap()">Conectarse</button>
            </div>
            <div class="toggle-panel toggle-right">
              <h1>E V O bank</h1>
              <p>¿Aún no tienes cuenta?</p>
              <button type="button" class="hidden" id="register" @click="swap()">Crear
                cuenta</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ServiceLogin from '@/services/ServiceLogin';
const service = new ServiceLogin();

export default {
  name: "LoginComponent",
  data() {
    return {
      isSignDiv: false,
      signUpObj: {
        name: '',
        email: '',
        password: ''
      },
      userName: '',
      password: ''
    }
  },
  mounted() {

  },
  methods: {
    swap() {
      this.isSignDiv = !this.isSignDiv;
    },
    login(){
      service.getToken(this.userName, this.password).then(response=>{
        service.token = response.response;
        console.log("fetch:" + service.fetchToken());
        this.$router.push('/perfil/'+ this.password);
      })
    }
  }
}
</script>

<style>
@import "../assets/css/login.css";
</style>
