// angular/a6authlogin/src/app/components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { environment } from '../../../environments/environment';
import { Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent {
  constructor(private _router: Router) { }

  get isLogin(): boolean {
    return environment.isLogged;
  }

  logout() {
    environment.isLogged = false;
    this._router.navigate(['/login']);
  }
}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" [routerLink]="['/']">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                @if (isLogin){
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/perfil']">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <button class="nav-link" (click)="logout()">Logout</button>
                    </li>
                } @else {
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/login']">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" [routerLink]="['/register']">Register</a>
                    </li>
                }
                
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        CRUDS
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" [routerLink]="['/coches']">Coches</a></li>
                        <li><a class="dropdown-item" [routerLink]="['/plantillas']">complex</a></li>
                    </ul>
                </li> -->
            </ul>
        </div>
    </div>
</nav>

// vue/vue08login/src/components/MenuComponent.vue
<template>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container-fluid">
            <router-link class="navbar-brand" to="/">Series 🐲</router-link>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
                aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExample03">
                <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                    <li class="nav-item">
                        <router-link class="nav-link active" aria-current="page" to="/">Home</router-link>
                    </li>
                    <li class="nav-item">
                        <router-link class="nav-link" to="/login">Login</router-link>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<script>
export default {
    name: "MenuComponent",
    data() {
        return {

        }
    },
    mounted() {

    }
}
</script>

<style></style>
